---
extends:
  - standard
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended
rules:
  node/shebang: off
settings:
  node:
    allowModules:
      - electron
      - "@gyselroth/windows-fsstat"
